### ISSUE TITLE
Pass the resource key role as a module input

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-instances#206]
### Description

Currently hardcoded to "Manager" - eg: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/blob/main/main.tf#L54

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamar7** [comment]
Closing the issue since the PR is merged.
