### ISSUE TITLE
Update naming in module to adjust with latest

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-instances#208]
### Description

LogDNA -> Log Analysis
Sysdig -> IBM Cloud Monitoring

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
Do we want to rename variable names (breaking change) or just documentation?

**Comment by iamar7** [comment]
@vburckhardt I am assuming that we want to change the variable names and proceeding ahead as per it.

**Comment by iamar7** [comment]
https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/221

**Comment by iamar7** [comment]
> #221

Closed this PR as this issue will require a re-write of the entire code after the [observability module is breakdown into individual components](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/issues/212) is merged.

**Comment by shemau** [comment]
A lot of the variables (input and outputs) for submodules were renamed as part of the refactor. Hopefully that makes updates easier.

**Comment by iamar7** [comment]
PR Merged
