### ISSUE TITLE
Break down observability module into individual components

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-instances#212]
### Description

Break the top level module into submodules:
- logdna
- sysdig
- activity tracker

Couple of reasons:
- Code base is starting to become large. See for instance addition of at routing at https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/155
- Some consumers have a stricter separation when separate logdna and sysdig teams. Whilst the current module has got boolean to enable / disable some capabilities, it'd be cleaner to have dedicated module doing one thing only.

The top module should ideally be backwards compatible - see to use of move blocks. https://developer.hashicorp.com/terraform/language/modules/develop/refactoring

### New or affected modules

- [terraform-ibm-observability-instances](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances)

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Soaib024** [comment]
PR merged - hence closing
