### ISSUE TITLE
AT routing support

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-instances#213]
### Description

Tracking existing ongoing work at https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/155

### New or affected modules

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Soaib024** [comment]
@vburckhardt It's parked for now until a new logging agent is rolled out
So, we can close this for now

**Comment by Soaib024** [comment]
PR merged - hence closing
