### ISSUE TITLE
Change default value of instance name in examples

### ISSUE THREAD

**Issue by Soaib024** [terraform-ibm-modules/terraform-ibm-observability-instances#224]
### Description

Currently default value of the instance name in examples is set to`${var.prefix}` which will create activity tracker, logdna and sysdig with same name, it will be better if default values are set to something like `${var.prefix}-at` , `${var.prefix}-logdna` and `${var.prefix}-sysdig`

**Not a priority issue**

### New or affected modules

https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by iamar7** [comment]
Tackling this issue in this PR: https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/pull/259

**Comment by iamar7** [comment]
> Tackling this issue in this PR: #259

Since modifying this was causing upgrade test failure in the above PR so created a new PR just for the instance name updation.

**Comment by iamar7** [comment]
PR merged closing
