### ISSUE TITLE
Activity tracker target variables should be marked as sensitive

### ISSUE THREAD

**Issue by vburckhardt** [terraform-ibm-modules/terraform-ibm-observability-instances#270]
There is an optional api_key in the blob.

https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/blob/f1754c67e86e98669569e325209852de61d50850/modules/activity_tracker/variables.tf#L100

    api_key                    = optional(string)

**Comment by Khuzaima05** [comment]
PR merged
