### ISSUE TITLE
Add support to tag resource manager keys

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#29]
### Description

Currently there is no support to tag the resource manager keys being created by this module. The `ibm_resource_key` resource has support to pass a `tags` value to it, so we should expose this as input variables (probably one for each observability instance type - e.g. `logdna_key_tags`, `sysdig_key_tags` etc etc).

### New or affected modules

terraform-ibm-observability-instances

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by MatthewLemmond** [comment]
Closing this issue, PR merged.
