### ISSUE TITLE
[terraform-ibm-observability-instances] Doc updates required

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#416]
https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/activity_tracker
- usage source is wrong -> `"terraform-ibm-modules/observability/ibm"`

https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/cloud_monitoring
- usage source is wrong -> `"terraform-ibm-modules/observability/ibm"`

https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/log_analysis
- usage source is wrong -> `"terraform-ibm-modules/observability-instances/ibm"`

Lets review the full doc while making these changes

**Comment by mounika-nalla** [comment]
Closing as PR merged.
