### ISSUE TITLE
Add support to create the atracker to COS s2s auth policy

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#421]
Add support to create the atracker to COS auth policy:

for example:
```
resource "ibm_iam_authorization_policy" "atracker_cos" {
  count                       = var.skip_atracker_cos_iam_auth_policy ? 0 : 1
  source_service_name         = "atracker"
  target_service_name         = "cloud-object-storage"
  target_resource_instance_id = module.cos.cos_instance_guid
  roles                       = ["Object Writer"]
  description                 = "Permit AT service Object Writer access to COS instance ${module.cos.cos_instance_id}"
}
```

The count should also take into consieration the value of `cos_targets.service_to_service_enabled`. If this is true and `skip_atracker_cos_iam_auth_policy` is `false`, then create the auth policy.

The docs recommend the use s2s auth over IAM apikey auth (no apikey rotation to worry about) so we should update the [observability_at_event_routing example](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/examples/observability_at_event_routing) to use s2s for the COS target instead of apikey

**Comment by Aashiq-J** [comment]
Pr merged. Closing issue.
