### ISSUE TITLE
Provide the flexibility to enable archiving for logdna OR AT 

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#507]
There is currently 1 variable called `enable_archive` which is used for both logdna and AT. Can we split this into two to allow more flexibility. 
Propose to replace `enable_archive` with `log_analysis_enable_archive` and `activity_tracker_enable_archive` in the root level module

**Comment by Khuzaima05** [comment]
PR merged, Closing this issue
