### ISSUE TITLE
Expose logdna instance resource service key

### ISSUE THREAD

**Issue by shemau** [terraform-ibm-modules/terraform-ibm-observability-instances#52]
### Description

Expose the manager service key for the LogDNA instance, in the same way as the Activity Tracker service key is exposed.

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by ocofaigh** [comment]
@shemau This is in now right? `logdna_resource_key` is an available output
