### ISSUE TITLE
Error: Invalid index in terraform/modules/log_analysis/modules/log_analysis/outputs.tf line 22

### ISSUE THREAD

**Issue by lionelmace** [terraform-ibm-modules/terraform-ibm-observability-instances#526]
IBM Cloud TF Provider 1.66.0
Terraform 1.6

I face the following error:
```
Error: Invalid index
on .terraform/modules/log_analysis/modules/log_analysis/outputs.tf line 22, in output "resource_key":
  value       = length(ibm_resource_key.resource_key) > 0 ? ibm_resource_key.resource_key[0].credentials["service_key"] : null
The given key does not identify an element in this collection value.
```

<img width="879" alt="image" src="https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/assets/12241613/d48640f2-aeea-473c-9bf6-7c873c3a4e17">

I have been using this module in my full landing zone. This issue started to appear recently without any change. Here is how I use it
https://github.com/lionelmace/ibm-cloud-native/blob/main/terraform/observability-logging.tf.onhold

---

By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/terraform-ibm-modules/documentation/blob/main/CODE_OF_CONDUCT.md)

**Comment by Aashiq-J** [comment]
@lionelmace ,
Can you confirm if you are still facing this issue?
I ran the code you mentioned in the issue multiple times in my local setup with terraform version 1.6.6
I wasn't able to reproduce the error.

**Comment by lionelmace** [comment]
I could not reproduce the issue today. Closing it.
