### ISSUE TITLE
Create metrics_router submodule

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#555]
- Add a submodule in https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules called `metrics_routing`.
- The module will be similar to the [activity_tracker](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances/tree/main/modules/activity_tracker) one in that it will support creating a target and a route. 
- The provider already has support for this with `ibm_metrics_router_route`, `ibm_metrics_router_target` and `ibm_metrics_router_settings`

**Comment by iamar7** [comment]
PR Merged.
