### ISSUE TITLE
Add support to use Event Streams ATracker s2s auth policy

### ISSUE THREAD

**Issue by ocofaigh** [terraform-ibm-modules/terraform-ibm-observability-instances#581]
In https://github.com/IBM-Cloud/terraform-provider-ibm/pull/5605 service to service auth policy support was added when creating an Event Streams ATracker target. Up until now it always required an apikey. This came in the `1.70.0` provider release, so we should expose this feature now in:

- public `terraform-ibm-observability-instances` repo
- internal `observability-instances-module` repo

Ensure to bump the required ibm provider version to `>=1.70.0, <2.0.0`

**Comment by iamar7** [comment]
@ocofaigh before making similar changes to the internal module, I need to update the [version](https://github.ibm.com/GoldenEye/observability-instances-module/blob/b16bc66331bcc5952dd17f24b972f36d52b98727/main.tf#L86) of the internal observability-instance module to point to the latest external release [3.0.3](https://github.com/terraform-ibm-modules/terraform-ibm-observability-instances) which in turn requires complete removal of support for `log_analysis` and `AT`. 

So shall I proceed with this changes?

**Comment by iamar7** [comment]
PR Merged
